### ISSUE TITLE
 sqlboiler mysql can not find the templates and templates_test folder in my project source

### ISSUE THREAD

**Issue by dtrehas** [volatiletech/sqlboiler#188] opened 2017-08-16 18:09 UTC
Dear Aaron,
thank you for your wonderful project.
Thought I bumped on something: 

_Error: unable to initialize templates: template: pattern matches no files: `xxx\gopath\src\yyy\templates\*.tpl`_

when I used the command : **sqlboiler mysql** 

SQLBoiler version: 2.5.1 

I had to copy by hand templates, and templates_test in my project source (aka xxx\gopath\src\yyy\templates and templates_test

Thank you in advance

**Comment by aarondl** [comment] 2017-08-17 02:06
Hey there @dtrehas, thanks for the praise. The problem is that currently the templates are required in the GOPATH. This is an assumption made by `sqlboiler` that you've used `go get` to download these. You can also override this with the `--basedir` flag. We will be changing this to be built into the binary using `bindata`. See the discussion here: https://github.com/volatiletech/sqlboiler/issues/151

I'll close this issue because I think it's working as expected, and the problem you've encountered will eventually be fixed by the `bindata` work. Re-open if you have any further concerns, thanks :D

**Closed by aarondl** 2017-08-17 02:06 UTC
