### ISSUE TITLE
From's default behavior is to 'append' instead of 'set'

### ISSUE THREAD

**Issue by tstrg** [volatiletech/sqlboiler#73] opened 2016-11-30 11:50 UTC
Hi,I'm new in go,

and I would like to try SQLBoiler. I generated models. I used two tables "users" and "apps".
All works as expected on the following query:

```
  user, err := models.Users(dbSes,
  Select("u.reference_id","u.id","u.app_id"),
  From("users as u"),
  Where("u.reference_id = ?", "dhynek"),
).One()	
```

when I add the inner join to the query

```
  user, err := models.Users(dbSes,
  Select("u.reference_id","u.id","u.app_id"),
  From("users as u"),
  InnerJoin("apps a ON a.id = u.app_id"),
  Where("u.reference_id = ?", "dhynek"),
).One()	
```

I'm getting error:
`models: failed to execute a one query for users: bind failed to execute query: Error 1054: Unknown column 'u.app_id' in 'on clause'`

Could you please help me to debug this issue? Working  MySQL qu

```
SELECT
	u.id				userUuid,
	u.reference_id	referenceId
FROM
	users u
LEFT JOIN apps a ON u.app_id = a.id
WHERE
	u.reference_id = "xxxxxx"
AND a.app_key="yyyyy"
```

Thank you,
Tomas

**Comment by aarondl** [comment] 2016-11-30 16:21
Hey Tomas, in SQLBoiler the first thing to do to debug queries is to turn debug mode on and run your query again.

Please refer to the documentation here: https://github.com/vattle/sqlboiler#diagnosing-problems
At the bottom of that section it tells you how to enable it.

Post the output here please :)

**Comment by aarondl** [comment] 2016-12-06 06:11
I've actually enabled debug mode and tried a similar query and found an issue here.

Two workarounds for now:

This one utilizes lower level helpers to achieve your query:
```go
query := models.Users(dbSes,
  Select("u.reference_id","u.id","u.app_id"),
  InnerJoin("apps a ON a.id = u.app_id"),
  Where("u.reference_id = ?", "dhynek"),
)

queries.SetFrom(query, "users as u")
user, err := query.One()
...
```

This one simply does less work than your query, since `users` is automatically added to the from anyway, but forces us to use full names in the select:
```go
users, err := models.Users(dbSes,
  Select("users.reference_id", "users.id", "users.app_id"),
  InnerJoin("apps a ON a.id = users.app_id"),
  Where("users.reference_id = ?", "dhynek"),
)
```

Working on a real resolution. Might be API breaking though.

**Comment by tstrg** [comment] 2016-12-06 13:48
Thank you for the response, I'll look into it.

**Comment by aarondl** [comment] 2016-12-20 03:45
The workarounds will have to suffice until v3. Since this is a breaking change.

**Comment by aarondl** [comment] 2017-11-16 07:34
After meditating on this for a while, I don't think there's a good solution other than using the workarounds I've outlined above.

The problem is:
When you create a query using `models.Users` you will get an automatic `qm.From("models"."Users")` which is fine on its own. The problem is when you add the explicit `From` in order to use short-form names for your select list, you end up with two from clauses.

The workarounds are:
1. Don't use short form names, since the automatic from is fully qualified you can use `users.column` to solve the issue
2. Override using `SetFrom`

The solutions I pondered were:
1. Doing a detection for previous From clauses before setting the automatic one. This is bad for the following reasons:
    1. You may have not tried to override, but instead added a supplemental From clause, and now it's no longer providing the first one, this is surprising behavior.
    2. It can still be trampled by an additional From in a second Apply, so it's not even fullproof.
2. Changing the From to do a set by default, this is bad because it kills any froms you provide

In essence, I don't think the solutions are better than the current world and aren't worth the price we'd pay for them. So I'm going to close this. Thanks for filing :)

**Closed by aarondl** 2017-11-16 07:34 UTC
Labels: v3
