### ISSUE TITLE
Incomplete eager loading result with nested many-to-many relationships

### ISSUE THREAD

**Issue by inoc603** [volatiletech/sqlboiler#756] opened 2020-05-24 12:50 UTC
### What version of SQLBoiler are you using (`sqlboiler --version`)?

v4.1.2

### What is your database and version (eg. Postgresql 10)

mysql 5.7

### If this happened at runtime what code produced the issue? (if not applicable leave blank)

```go
package main

import (
        "context"
        "database/sql"
        "fmt"
        "time"

        "github.com/inoc603/issue/models"
        _ "github.com/go-sql-driver/mysql"
        "github.com/volatiletech/sqlboiler/v4/boil"
        "github.com/volatiletech/sqlboiler/v4/queries/qm"
)

func main() {
        db, err := sql.Open("mysql", "root:toor@tcp(127.0.0.1:3306)/sqlboiler?parseTime=true")
        panicOnError(err)

        ctx := context.TODO()

        b := &models.BRow{
                ID: time.Now().UnixNano(),
        }
        panicOnError(b.Insert(ctx, db, boil.Whitelist(models.BRowColumns.ID)))

        a1 := &models.ARow{}
        panicOnError(a1.Insert(ctx, db, boil.Infer()))

        a2 := &models.ARow{}
        panicOnError(a2.Insert(ctx, db, boil.Infer()))

        c1 := &models.CRow{}
        panicOnError(c1.Insert(ctx, db, boil.Infer()))

        c2 := &models.CRow{}
        panicOnError(c2.Insert(ctx, db, boil.Infer()))

        fmt.Println(a1, a2, c1, c2, b)

        panicOnError(b.AddCRows(ctx, db, false, c1, c2))
        panicOnError(b.AddARows(ctx, db, false, a1, a2))

        aSlice, err := models.ARows(
                qm.Load(qm.Rels(models.ARowRels.BRows, models.BRowRels.CRows)),
        ).All(ctx, db)

        for _, a := range aSlice {
                fmt.Printf("A(%d)(%p)\n", a.ID, a)
                for _, b := range a.R.BRows {
                        fmt.Printf("- B(%d)(%p)\n", b.ID, b)
                        for _, c := range b.R.CRows {
                                fmt.Printf("  - C(%d)(%p)\n", c.ID, c)
                        }
                }
        }
}

func panicOnError(err error) {
        if err != nil {
                panic(err)
        }
}
```

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)

```sql
create table `a_row` (
`id` bigint(20) unsigned not null auto_increment ,
`created_at` timestamp not null  default current_timestamp ,
`updated_at` timestamp not null on update current_timestamp default current_timestamp ,
primary key (id)
) engine=innodb charset=utf8 comment="a_row";

create table `b_row` (
`id` bigint(20) unsigned not null auto_increment  ,
`created_at` timestamp not null  default current_timestamp ,
`updated_at` timestamp not null on update current_timestamp default current_timestamp ,
primary key (id)
) engine=innodb charset=utf8 comment="b_row";

create table `c_row` (
`id` bigint(20) unsigned not null auto_increment comment,
`created_at` timestamp not null  default current_timestamp comment ,
`updated_at` timestamp not null on update current_timestamp default current_timestamp ,
primary key (id)
) engine=innodb charset=utf8 comment="c_row";

create table `join_a_row_b_row` (
`a_row_id` bigint(20) unsigned not null  comment 'a_row_id' ,
`b_row_id` bigint(20) unsigned not null  comment 'b_row_id' ,
primary key (a_row_id, b_row_id)
) engine=innodb charset=utf8 comment="join_a_row_b_row";

create table `join_b_row_c_row` (
`b_row_id` bigint(20) unsigned not null  comment 'b_row_id' ,
`c_row_id` bigint(20) unsigned not null  comment 'c_row_id' ,
primary key (b_row_id, c_row_id)
) engine=innodb charset=utf8 comment="join_b_row_c_row";

alter table `join_a_row_b_row` add foreign key (`a_row_id`) references `a_row`(`id`);
alter table `join_a_row_b_row` add foreign key (`b_row_id`) references `b_row`(`id`);
alter table `join_b_row_c_row` add foreign key (`b_row_id`) references `b_row`(`id`);
alter table `join_b_row_c_row` add foreign key (`c_row_id`) references `c_row`(`id`);
```

### Further information. What did you do, what did you expect?

I have a simple schema with 2 many-to-many relationships:

```
a -[m: m]-> b -> [m: m] -> c
```

With these data:

```
a1 -> b1
a2 -> b1
b1 -> c1
b2 -> c2
```

When I query with eager loading:

```go
        aSlice, err := models.ARows(
                qm.Load(qm.Rels(models.ARowRels.BRows, models.BRowRels.CRows)),
        ).All(ctx, db)
```

I expect to get a result like:

```
A(1)
- B(1)
  - C(1)
  - C(2)
A(2)
- B(1)
  - C(1)
  - C(2)
```

But I got:

```
A(1)
- B(1)
  - C(1)
  - C(2)
A(2)
- B(1)
```

The second layer of relationship is only available in the first result.

**Comment by inoc603** [comment] 2020-05-25 03:01
In the generated `LoadXXX` method, it seems that the code breaks out of the loop early when assigning the results. It looks like the code assumes each `foreign` will only match one `local`.

```go
        for i, foreign := range resultSlice {
                localJoinCol := localJoinCols[i]
                for _, local := range slice {
                        if local.ID == localJoinCol {
                                local.R.BRows = append(local.R.BRows, foreign)
                                if foreign.R == nil {
                                        foreign.R = &bRowR{}
                                }
                                foreign.R.CRows = append(foreign.R.CRows, local)
                                break // Remove this seems to solve the problem
                        }
                }
        }
```

**Comment by aarondl** [comment] 2020-06-17 23:11
We've had a long standing bug in the code when it comes to this stuff. See here for details:
https://github.com/volatiletech/sqlboiler/issues/457

Eager loading really needs a rewrite :(

We have this crazy trade-off problem. Right now it attempts to be very memory efficient by gathering up all the IDs so that none are loaded two times from the database (prevents things like: `where id in (1,1,1,1,1)`). The problem is that re-using these pieces of memory ends up adding duplicates.

Closing as duplicate of #457

**Closed by aarondl** 2020-06-17 23:11 UTC

**Comment by mmendez512** [comment] 2020-07-21 14:18
@aarondl we have a few nested M2M tables. Is there a work around for this issue? Sorry, I'm pretty new to using the lib and still trying to figure out the landscape.

Thanks.

**Comment by aarondl** [comment] 2020-07-25 15:42
@mmendez512 unfortunately the only workaround is to fall back to raw queries at the moment.

**Comment by mmendez512** [comment] 2020-07-26 21:55
OK, thanks for the reply back
