### ISSUE TITLE
Print stdout/stderr when calling external command fails

### ISSUE THREAD

**Issue by lunemec** [volatiletech/sqlboiler#371] opened 2018-08-17 16:19 UTC
### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v3.0.0-rc10

When running tests:
```
go test ./models
```
it failed on:
```
failed to wait for mysqldump command: exit status 2
```
The problem is, the mysqldump printed out the errors when you ran it by hand. For ease of debugging, I thing the stderr (at least) should be captured and printed on error.

This is the line from generated test that should be different:
```go
	if err = dumpCmd.Wait(); err != nil {
		fmt.Println(err)
		return errors.Wrap(err, "failed to wait for mysqldump command")
	}
```

Probably something similar to this:
https://golang.org/pkg/os/exec/#Cmd.StderrPipe

Thanks for this library!

**Comment by aarondl** [comment] 2018-08-17 17:00
Duplicate of #224. You're welcome for the library! Hope it's helping in some way.

**Closed by aarondl** 2018-08-17 17:00 UTC
