### ISSUE TITLE
"=NULL" vs "IS NULL"

### ISSUE THREAD

**Issue by pennersr** [volatiletech/sqlboiler#417] opened 2018-11-05 13:44 UTC
Suppose you have a NULLable column `bar`.  Then this query won't give any results:

`SELECT * FROM foo WHERE bar=NULL`

It needs to be written as:

`SELECT * FROM foo WHERE bar IS NULL`

Now, on sqlboiler this poses a problem, as queries are typically constructed like this:

```
bar := GetBar()
models.Foos(qm.Where("bar=?", bar)).One()
```

The above leads to unexpected results, and properly handling this requires a lot of boilerplate. What is needed here is something like: 

```
bar := GetBar()
models.Foos(qm.WhereEQ("bar", bar)).One()
```
Then, if the specified `bar` is `nil` it would use `IS NULL`. Is there anything that can be done inside sqlboiler to facilitate for this?

**Comment by aarondl** [comment] 2018-11-15 03:18
I agree wholeheartedly that it should be something supported out of the box. I've been dreaming of #426 for a while now though I have not implemented it. It's much cleaner than the system that's currently present even though a bit verbose. Additionally protects against bad types being used in where clauses which is also great. To be 100% transparent: I'm not looking to add this feature myself anytime soon as I've other things on the go right now but I'd be happy to help someone work through it.

**Comment by aarondl** [comment] 2019-01-02 17:47
Closing as duplicate of #426

**Closed by aarondl** 2019-01-02 17:47 UTC
