### ISSUE TITLE
malfunction of imports.all

### ISSUE THREAD

**Issue by saulortega** [volatiletech/sqlboiler#321] opened 2018-06-28 15:27 UTC
### What version of SQLBoiler are you using (`sqlboiler --version`)?

SQLBoiler v3.0.0-rc9

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)

go:generate sqlboiler psql -d

Imports in all models after normal generation:

```go
import (
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/strmangle"
	"gopkg.in/volatiletech/null.v7"
)
```

Added to toml:

```
[imports.all]
  standard = ['"gopkg.in/volatiletech/null.v7"']
  third_party = ['"nulo"']
```

Imports after generation with previous toml config:

```go
import (
	"gopkg.in/volatiletech/null.v7"
	"strconv"
	"time"

	"nulo"
)
```

**Comment by aarondl** [comment] 2018-06-28 15:36
Hey Saul. This is actually working as intended. It functions as a total override not as an addition.

Also third party means "not go standard library" so both null and nulo belong in third party.

Go take a look at imports.go and steal the default "all" as your starting point and then you can add your own. Closing for now. Let me know if there's other problems.

**Closed by aarondl** 2018-06-28 15:36 UTC

**Comment by saulortega** [comment] 2018-06-28 15:52
Oh, now I understand
