### ISSUE TITLE
composite primary key (where FK is part of the PK) results in incorrect models

### ISSUE THREAD

**Issue by mikewiacek** [volatiletech/sqlboiler#772] opened 2020-06-08 20:51 UTC
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
v3.7.1

### What is your database and version (eg. Postgresql 10)
postgres 11

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)

sqlboiler --no-hooks --no-tests psql

### What is the output of the command above with the `-d` flag added to it? (Provided you are comfortable sharing this, it contains a blueprint of your schema)

`{"config":{"driver_name":"psql","driver_config":{"blacklist":null,"dbname":"new_database","host":"35.184.200.91","pass":"pokerchipsARERED","port":5432,"schema":"public","user":"postgres","whitelist":null},"pkg_name":"models","out_folder":"models","debug":true,"no_tests":true,"no_hooks":true,"struct_tag_casing":"snake","imports":{"all":{"Standard":["\"database/sql\"","\"fmt\"","\"reflect\"","\"strconv\"","\"strings\"","\"sync\"","\"time\"","\"context\""],"ThirdParty":["\"github.com/friendsofgo/errors\"","\"github.com/volatiletech/sqlboiler/boil\"","\"github.com/volatiletech/sqlboiler/queries\"","\"github.com/volatiletech/sqlboiler/queries/qm\"","\"github.com/volatiletech/sqlboiler/queries/qmhelper\"","\"github.com/volatiletech/sqlboiler/strmangle\""]},"test":{"Standard":["\"bytes\"","\"reflect\"","\"testing\"","\"context\""],"ThirdParty":["\"github.com/volatiletech/sqlboiler/boil\"","\"github.com/volatiletech/sqlboiler/queries\"","\"github.com/volatiletech/sqlboiler/randomize\"","\"github.com/volatiletech/sqlboiler/strmangle\""]},"singleton":{"boil_queries":{"Standard":null,"ThirdParty":["\"github.com/volatiletech/sqlboiler/drivers\"","\"github.com/volatiletech/sqlboiler/queries\"","\"github.com/volatiletech/sqlboiler/queries/qm\""]},"boil_types":{"Standard":["\"strconv\""],"ThirdParty":["\"github.com/friendsofgo/errors\"","\"github.com/volatiletech/sqlboiler/boil\"","\"github.com/volatiletech/sqlboiler/strmangle\""]},"psql_upsert":{"Standard":["\"fmt\"","\"strings\""],"ThirdParty":["\"github.com/volatiletech/sqlboiler/drivers\"","\"github.com/volatiletech/sqlboiler/strmangle\""]}},"test_singleton":{"boil_main_test":{"Standard":["\"database/sql\"","\"flag\"","\"fmt\"","\"math/rand\"","\"os\"","\"path/filepath\"","\"strings\"","\"testing\"","\"time\""],"ThirdParty":["\"github.com/spf13/viper\"","\"github.com/volatiletech/sqlboiler/boil\""]},"boil_queries_test":{"Standard":["\"bytes\"","\"fmt\"","\"io\"","\"io/ioutil\"","\"math/rand\"","\"regexp\""],"ThirdParty":["\"github.com/volatiletech/sqlboiler/boil\""]},"boil_suites_test":{"Standard":["\"testing\""],"ThirdParty":null},"psql_main_test":{"Standard":["\"bytes\"","\"database/sql\"","\"fmt\"","\"io\"","\"io/ioutil\"","\"os\"","\"os/exec\"","\"regexp\"","\"strings\""],"ThirdParty":["\"github.com/friendsofgo/errors\"","\"github.com/kat-co/vala\"","_ \"github.com/lib/pq\"","\"github.com/spf13/viper\"","\"github.com/volatiletech/sqlboiler/drivers/sqlboiler-psql/driver\"","\"github.com/volatiletech/sqlboiler/randomize\""]},"psql_suites_test":{"Standard":["\"testing\""],"ThirdParty":[]}},"based_on_type":{"null.Bool":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/null\""]},"null.Bytes":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/null\""]},"null.Float32":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/null\""]},"null.Float64":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/null\""]},"null.Int":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/null\""]},"null.Int16":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/null\""]},"null.Int32":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/null\""]},"null.Int64":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/null\""]},"null.Int8":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/null\""]},"null.JSON":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/null\""]},"null.String":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/null\""]},"null.Time":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/null\""]},"null.Uint":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/null\""]},"null.Uint16":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/null\""]},"null.Uint32":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/null\""]},"null.Uint64":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/null\""]},"null.Uint8":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/null\""]},"pgeo.Box":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"pgeo.Circle":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"pgeo.Line":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"pgeo.Lseg":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"pgeo.NullBox":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"pgeo.NullCircle":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"pgeo.NullLine":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"pgeo.NullLseg":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"pgeo.NullPath":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"pgeo.NullPoint":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"pgeo.NullPolygon":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"pgeo.Path":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"pgeo.Point":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"pgeo.Polygon":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types/pgeo\""]},"time.Time":{"Standard":["\"time\""],"ThirdParty":[]},"types.BoolArray":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types\""]},"types.BytesArray":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types\""]},"types.Decimal":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types\""]},"types.DecimalArray":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types\""]},"types.Float64Array":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types\""]},"types.HStore":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types\""]},"types.Int64Array":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types\""]},"types.JSON":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types\""]},"types.NullDecimal":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types\""]},"types.StringArray":{"Standard":[],"ThirdParty":["\"github.com/volatiletech/sqlboiler/types\""]}}},"aliases":{"tables":{"building":{"up_plural":"Buildings","up_singular":"Building","down_plural":"buildings","down_singular":"building","columns":{"building_id":"BuildingID","name":"Name"}},"hobbies":{"up_plural":"Hobbies","up_singular":"Hobby","down_plural":"hobbies","down_singular":"hobby","columns":{"hobby_id":"HobbyID","hobby_name":"HobbyName"}},"resident_hobbies":{"up_plural":"ResidentHobbies","up_singular":"ResidentHobby","down_plural":"residentHobbies","down_singular":"residentHobby","columns":{"building_id":"BuildingID","hobby_id":"HobbyID","name":"Name"},"relationships":{"hobbies_fk":{"local":"ResidentHobbies","foreign":"Hobby"},"residents_fk":{"local":"BuildingResidentHobbies","foreign":"Building"}}},"residents":{"up_plural":"Residents","up_singular":"Resident","down_plural":"residents","down_singular":"resident","columns":{"building_id":"BuildingID","name":"Name"},"relationships":{"building_fk":{"local":"Residents","foreign":"Building"}}}}},"version":"3.7.1"},"driver_config":{"blacklist":null,"dbname":"new_database","host":"35.184.200.91","pass":"pokerchipsARERED","port":5432,"schema":"public","user":"postgres","whitelist":null},"schema":"public","dialect":{"lq":34,"rq":34,"use_index_placeholders":true,"use_last_insert_id":false,"use_schema":false,"use_default_keyword":true,"use_auto_columns":false,"use_top_clause":false,"use_output_clause":false,"use_case_when_exists_clause":false},"tables":[{"name":"building","schema_name":"","columns":[{"name":"building_id","type":"int64","db_type":"bigint","default":"nextval('building_building_id_seq'::regclass)","nullable":false,"unique":true,"validated":false,"arr_type":null,"udt_name":"int8","domain_name":null,"full_db_type":"int8","auto_generated":false},{"name":"name","type":"null.String","db_type":"text","default":"","nullable":true,"unique":false,"validated":false,"arr_type":null,"udt_name":"text","domain_name":null,"full_db_type":"text","auto_generated":false}],"p_key":{"name":"building_pk","columns":["building_id"]},"f_keys":null,"is_join_table":false,"to_one_relationships":null,"to_many_relationships":[{"name":"building_fk","table":"building","column":"building_id","nullable":false,"unique":true,"foreign_table":"residents","foreign_column":"building_id","foreign_column_nullable":false,"foreign_column_unique":false,"to_join_table":false,"join_table":"","join_local_fkey_name":"","join_local_column":"","join_local_column_nullable":false,"join_local_column_unique":false,"join_foreign_fkey_name":"","join_foreign_column":"","join_foreign_column_nullable":false,"join_foreign_column_unique":false}]},{"name":"hobbies","schema_name":"","columns":[{"name":"hobby_id","type":"int64","db_type":"bigint","default":"nextval('hobbies_hobby_id_seq'::regclass)","nullable":false,"unique":true,"validated":false,"arr_type":null,"udt_name":"int8","domain_name":null,"full_db_type":"int8","auto_generated":false},{"name":"hobby_name","type":"string","db_type":"text","default":"","nullable":false,"unique":false,"validated":false,"arr_type":null,"udt_name":"text","domain_name":null,"full_db_type":"text","auto_generated":false}],"p_key":{"name":"hobbies_pk","columns":["hobby_id"]},"f_keys":null,"is_join_table":false,"to_one_relationships":null,"to_many_relationships":[{"name":"hobbies_fk","table":"hobbies","column":"hobby_id","nullable":false,"unique":true,"foreign_table":"resident_hobbies","foreign_column":"hobby_id","foreign_column_nullable":false,"foreign_column_unique":false,"to_join_table":false,"join_table":"","join_local_fkey_name":"","join_local_column":"","join_local_column_nullable":false,"join_local_column_unique":false,"join_foreign_fkey_name":"","join_foreign_column":"","join_foreign_column_nullable":false,"join_foreign_column_unique":false}]},{"name":"resident_hobbies","schema_name":"","columns":[{"name":"hobby_id","type":"int64","db_type":"bigint","default":"","nullable":false,"unique":false,"validated":false,"arr_type":null,"udt_name":"int8","domain_name":null,"full_db_type":"int8","auto_generated":false},{"name":"name","type":"string","db_type":"text","default":"","nullable":false,"unique":false,"validated":false,"arr_type":null,"udt_name":"text","domain_name":null,"full_db_type":"text","auto_generated":false},{"name":"building_id","type":"int64","db_type":"bigint","default":"","nullable":false,"unique":false,"validated":false,"arr_type":null,"udt_name":"int8","domain_name":null,"full_db_type":"int8","auto_generated":false}],"p_key":{"name":"resident_hobbies_pk","columns":["hobby_id","name","building_id"]},"f_keys":[{"table":"resident_hobbies","name":"hobbies_fk","column":"hobby_id","nullable":false,"unique":false,"foreign_table":"hobbies","foreign_column":"hobby_id","foreign_column_nullable":false,"foreign_column_unique":true},{"table":"resident_hobbies","name":"residents_fk","column":"building_id","nullable":false,"unique":false,"foreign_table":"residents","foreign_column":"building_id","foreign_column_nullable":false,"foreign_column_unique":false},{"table":"resident_hobbies","name":"residents_fk","column":"building_id","nullable":false,"unique":false,"foreign_table":"residents","foreign_column":"name","foreign_column_nullable":false,"foreign_column_unique":false},{"table":"resident_hobbies","name":"residents_fk","column":"name","nullable":false,"unique":false,"foreign_table":"residents","foreign_column":"building_id","foreign_column_nullable":false,"foreign_column_unique":false},{"table":"resident_hobbies","name":"residents_fk","column":"name","nullable":false,"unique":false,"foreign_table":"residents","foreign_column":"name","foreign_column_nullable":false,"foreign_column_unique":false}],"is_join_table":false,"to_one_relationships":null,"to_many_relationships":null},{"name":"residents","schema_name":"","columns":[{"name":"building_id","type":"int64","db_type":"bigint","default":"","nullable":false,"unique":false,"validated":false,"arr_type":null,"udt_name":"int8","domain_name":null,"full_db_type":"int8","auto_generated":false},{"name":"name","type":"string","db_type":"text","default":"","nullable":false,"unique":false,"validated":false,"arr_type":null,"udt_name":"text","domain_name":null,"full_db_type":"text","auto_generated":false}],"p_key":{"name":"residents_pk","columns":["name","building_id"]},"f_keys":[{"table":"residents","name":"building_fk","column":"building_id","nullable":false,"unique":false,"foreign_table":"building","foreign_column":"building_id","foreign_column_nullable":false,"foreign_column_unique":true}],"is_join_table":false,"to_one_relationships":null,"to_many_relationships":[{"name":"residents_fk","table":"residents","column":"building_id","nullable":false,"unique":false,"foreign_table":"resident_hobbies","foreign_column":"building_id","foreign_column_nullable":false,"foreign_column_unique":false,"to_join_table":false,"join_table":"","join_local_fkey_name":"","join_local_column":"","join_local_column_nullable":false,"join_local_column_unique":false,"join_foreign_fkey_name":"","join_foreign_column":"","join_foreign_column_nullable":false,"join_foreign_column_unique":false},{"name":"residents_fk","table":"residents","column":"name","nullable":false,"unique":false,"foreign_table":"resident_hobbies","foreign_column":"building_id","foreign_column_nullable":false,"foreign_column_unique":false,"to_join_table":false,"join_table":"","join_local_fkey_name":"","join_local_column":"","join_local_column_nullable":false,"join_local_column_unique":false,"join_foreign_fkey_name":"","join_foreign_column":"","join_foreign_column_nullable":false,"join_foreign_column_unique":false},{"name":"residents_fk","table":"residents","column":"building_id","nullable":false,"unique":false,"foreign_table":"resident_hobbies","foreign_column":"name","foreign_column_nullable":false,"foreign_column_unique":false,"to_join_table":false,"join_table":"","join_local_fkey_name":"","join_local_column":"","join_local_column_nullable":false,"join_local_column_unique":false,"join_foreign_fkey_name":"","join_foreign_column":"","join_foreign_column_nullable":false,"join_foreign_column_unique":false},{"name":"residents_fk","table":"residents","column":"name","nullable":false,"unique":false,"foreign_table":"resident_hobbies","foreign_column":"name","foreign_column_nullable":false,"foreign_column_unique":false,"to_join_table":false,"join_table":"","join_local_fkey_name":"","join_local_column":"","join_local_column_nullable":false,"join_local_column_unique":false,"join_foreign_fkey_name":"","join_foreign_column":"","join_foreign_column_nullable":false,"join_foreign_column_unique":false}]}],"templates":[{"name":"templates/00_struct.go.tpl","loader":"asset:templates/00_struct.go.tpl"},{"name":"templates/01_types.go.tpl","loader":"asset:templates/01_types.go.tpl"},{"name":"templates/02_hooks.go.tpl","loader":"asset:templates/02_hooks.go.tpl"},{"name":"templates/03_finishers.go.tpl","loader":"asset:templates/03_finishers.go.tpl"},{"name":"templates/04_relationship_to_one.go.tpl","loader":"asset:templates/04_relationship_to_one.go.tpl"},{"name":"templates/05_relationship_one_to_one.go.tpl","loader":"asset:templates/05_relationship_one_to_one.go.tpl"},{"name":"templates/06_relationship_to_many.go.tpl","loader":"asset:templates/06_relationship_to_many.go.tpl"},{"name":"templates/07_relationship_to_one_eager.go.tpl","loader":"asset:templates/07_relationship_to_one_eager.go.tpl"},{"name":"templates/08_relationship_one_to_one_eager.go.tpl","loader":"asset:templates/08_relationship_one_to_one_eager.go.tpl"},{"name":"templates/09_relationship_to_many_eager.go.tpl","loader":"asset:templates/09_relationship_to_many_eager.go.tpl"},{"name":"templates/10_relationship_to_one_setops.go.tpl","loader":"asset:templates/10_relationship_to_one_setops.go.tpl"},{"name":"templates/11_relationship_one_to_one_setops.go.tpl","loader":"asset:templates/11_relationship_one_to_one_setops.go.tpl"},{"name":"templates/12_relationship_to_many_setops.go.tpl","loader":"asset:templates/12_relationship_to_many_setops.go.tpl"},{"name":"templates/13_all.go.tpl","loader":"asset:templates/13_all.go.tpl"},{"name":"templates/14_find.go.tpl","loader":"asset:templates/14_find.go.tpl"},{"name":"templates/15_insert.go.tpl","loader":"asset:templates/15_insert.go.tpl"},{"name":"templates/16_update.go.tpl","loader":"asset:templates/16_update.go.tpl"},{"name":"templates/17_upsert.go.tpl","loader":"base64:(sha256 of content): 397bf4cd7e448a0023fe2ecdf9b1c68065263280eb9b81966dfd356803fadd87"},{"name":"templates/18_delete.go.tpl","loader":"asset:templates/18_delete.go.tpl"},{"name":"templates/19_reload.go.tpl","loader":"asset:templates/19_reload.go.tpl"},{"name":"templates/20_exists.go.tpl","loader":"asset:templates/20_exists.go.tpl"},{"name":"templates/21_auto_timestamps.go.tpl","loader":"asset:templates/21_auto_timestamps.go.tpl"},{"name":"templates/singleton/boil_queries.go.tpl","loader":"asset:templates/singleton/boil_queries.go.tpl"},{"name":"templates/singleton/boil_table_names.go.tpl","loader":"asset:templates/singleton/boil_table_names.go.tpl"},{"name":"templates/singleton/boil_types.go.tpl","loader":"asset:templates/singleton/boil_types.go.tpl"},{"name":"templates/singleton/psql_upsert.go.tpl","loader":"base64:(sha256 of content): cb25b2a17877de034695accfb0a1f5f11437114d5f919062c792efee53cbb25f"},{"name":"templates_test/00_types.go.tpl","loader":"asset:templates_test/00_types.go.tpl"},{"name":"templates_test/all.go.tpl","loader":"asset:templates_test/all.go.tpl"},{"name":"templates_test/delete.go.tpl","loader":"asset:templates_test/delete.go.tpl"},{"name":"templates_test/exists.go.tpl","loader":"asset:templates_test/exists.go.tpl"},{"name":"templates_test/find.go.tpl","loader":"asset:templates_test/find.go.tpl"},{"name":"templates_test/finishers.go.tpl","loader":"asset:templates_test/finishers.go.tpl"},{"name":"templates_test/hooks.go.tpl","loader":"asset:templates_test/hooks.go.tpl"},{"name":"templates_test/insert.go.tpl","loader":"asset:templates_test/insert.go.tpl"},{"name":"templates_test/relationship_one_to_one.go.tpl","loader":"asset:templates_test/relationship_one_to_one.go.tpl"},{"name":"templates_test/relationship_one_to_one_setops.go.tpl","loader":"asset:templates_test/relationship_one_to_one_setops.go.tpl"},{"name":"templates_test/relationship_to_many.go.tpl","loader":"asset:templates_test/relationship_to_many.go.tpl"},{"name":"templates_test/relationship_to_many_setops.go.tpl","loader":"asset:templates_test/relationship_to_many_setops.go.tpl"},{"name":"templates_test/relationship_to_one.go.tpl","loader":"asset:templates_test/relationship_to_one.go.tpl"},{"name":"templates_test/relationship_to_one_setops.go.tpl","loader":"asset:templates_test/relationship_to_one_setops.go.tpl"},{"name":"templates_test/reload.go.tpl","loader":"asset:templates_test/reload.go.tpl"},{"name":"templates_test/select.go.tpl","loader":"asset:templates_test/select.go.tpl"},{"name":"templates_test/singleton/boil_main_test.go.tpl","loader":"asset:templates_test/singleton/boil_main_test.go.tpl"},{"name":"templates_test/singleton/boil_queries_test.go.tpl","loader":"asset:templates_test/singleton/boil_queries_test.go.tpl"},{"name":"templates_test/singleton/boil_suites_test.go.tpl","loader":"asset:templates_test/singleton/boil_suites_test.go.tpl"},{"name":"templates_test/singleton/psql_main_test.go.tpl","loader":"base64:(sha256 of content): 6dc1992498cb396d51c01d6cd844fe54cc03288dc886cd6bf6f333917f4c2b94"},{"name":"templates_test/singleton/psql_suites_test.go.tpl","loader":"base64:(sha256 of content): 10c471afd916418b4bfce8bafdfa4d2c01d100e1b078ee7fd065f3a143ba3ce7"},{"name":"templates_test/types.go.tpl","loader":"asset:templates_test/types.go.tpl"},{"name":"templates_test/update.go.tpl","loader":"asset:templates_test/update.go.tpl"},{"name":"templates_test/upsert.go.tpl","loader":"base64:(sha256 of content): fbdedf7ee38269da51adf562f603fb1616cf5ac7975c53268a9181863b2c2258"}]}`

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)

This is a dumb db schema to exhibit the problem. The schema defines a building, with a 1 to many relationship with residents. Residents has a composite pk, with the building_id (fk) being used as part of the resident's table PK, along with the resident's name. Then there is a many to many relationship between residents and another table called hobbies. This results in invalid go code being generated.

`CREATE TABLE public.building (
	building_id bigserial NOT NULL,
	name text,
	CONSTRAINT building_pk PRIMARY KEY (building_id)

);

CREATE TABLE public.residents (
	building_id bigint NOT NULL,
	name text NOT NULL,
	CONSTRAINT residents_pk PRIMARY KEY (name,building_id)

);

ALTER TABLE public.residents ADD CONSTRAINT building_fk FOREIGN KEY (building_id)
REFERENCES public.building (building_id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;

CREATE TABLE public.hobbies (
	hobby_id bigserial NOT NULL,
	hobby_name text NOT NULL,
	CONSTRAINT hobbies_pk PRIMARY KEY (hobby_id)

);

CREATE TABLE public.resident_hobbies (
	hobby_id bigint NOT NULL,
	name text NOT NULL,
	building_id bigint NOT NULL,
	CONSTRAINT resident_hobbies_pk PRIMARY KEY (hobby_id,name,building_id)

);

ALTER TABLE public.resident_hobbies ADD CONSTRAINT hobbies_fk FOREIGN KEY (hobby_id)
REFERENCES public.hobbies (hobby_id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE public.resident_hobbies ADD CONSTRAINT residents_fk FOREIGN KEY (name,building_id)
REFERENCES public.residents (name,building_id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
`

### Further information. What did you do, what did you expect?

The composite PK where an element is an FK and then more relationships that derive from that table seems to break sqlboiler's code generation. In this case you end up with stuff like:

`var ResidentHobbyRels = struct {
    Hobby    string
    Building string
    Building string
    Building string
    Building string
  }{
    Hobby:    "Hobby",
    Building: "Building",
    Building: "Building",
    Building: "Building",
    Building: "Building",
  }

  // residentHobbyR is where relationships are stored.
  type residentHobbyR struct {
    Hobby    *Hobby
    Building *Resident
    Building *Resident
    Building *Resident
    Building *Resident
  }  `

Having a composite PK including an FK shouldn't violate any normalization rules.

**Comment by mikewiacek** [comment] 2020-06-08 20:52
A copy of the schema in .sql form is here:

`CREATE TABLE public.building (
	building_id bigserial NOT NULL,
	name text,
	CONSTRAINT building_pk PRIMARY KEY (building_id)

);

CREATE TABLE public.residents (
	building_id bigint NOT NULL,
	name text NOT NULL,
	CONSTRAINT residents_pk PRIMARY KEY (name,building_id)

);

ALTER TABLE public.residents ADD CONSTRAINT building_fk FOREIGN KEY (building_id)
REFERENCES public.building (building_id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;

CREATE TABLE public.hobbies (
	hobby_id bigserial NOT NULL,
	hobby_name text NOT NULL,
	CONSTRAINT hobbies_pk PRIMARY KEY (hobby_id)

);

CREATE TABLE public.resident_hobbies (
	hobby_id bigint NOT NULL,
	name text NOT NULL,
	building_id bigint NOT NULL,
	CONSTRAINT resident_hobbies_pk PRIMARY KEY (hobby_id,name,building_id)

);

ALTER TABLE public.resident_hobbies ADD CONSTRAINT hobbies_fk FOREIGN KEY (hobby_id)
REFERENCES public.hobbies (hobby_id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE public.resident_hobbies ADD CONSTRAINT residents_fk FOREIGN KEY (name,building_id)
REFERENCES public.residents (name,building_id) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;


`

**Comment by aarondl** [comment] 2020-06-08 21:02
Duplicate of #698

**Closed by aarondl** 2020-06-08 21:02 UTC
