### ISSUE TITLE
Postgres 9.6 mismatched types int and int64

### ISSUE THREAD

**Issue by subvertallchris** [volatiletech/sqlboiler#517] opened 2019-04-23 17:58 UTC
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?

SQLBoiler 3.2.0

### If this happened at runtime what code produced the issue? (if not applicable leave blank)

It happens immediately upon `go run`, no specific code is related.

### Further information. What did you do, what did you expect?

I'm in the process of trying to connect models generated by SQLBoiler to a database I've been building/maintaining via Rails 5. When I `go run`, a few of the models complain about mismatched types, `int` (generated by SQLBoiler) vs `int64` (what's in the database, evidently.) I see issue #431, which poses a similar question about this, and the recommendation is to check the README, but I unfortunately do not understand what the README is trying to illustrate in its description of modifying generated types.

The error I'm receiving:

```
models/locations.go:852:16: invalid operation: local.ID == foreign.LocationID (mismatched types int and int64)
models/locations.go:1198:19: cannot use o.ID (type int) as type int64 in assignment
models/locations.go:1219:19: cannot use o.ID (type int) as type int64 in assignment
models/movements.go:734:16: invalid operation: local.ID == foreign.MovementID (mismatched types int and int64)
models/movements.go:932:19: cannot use o.ID (type int) as type int64 in assignment
models/movements.go:953:19: cannot use o.ID (type int) as type int64 in assignment
```

One of the models:

```go
// Location is an object representing the database table.
type Location struct {
	ID           int         `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name         null.String `boil:"name" json:"name,omitempty" toml:"name" yaml:"name,omitempty"`
	CreatedAt    time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt    time.Time   `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *locationR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L locationL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}
```

I've tried to find an example of someone using the config file to override detected types but I came up empty. Sorry to trouble you with what I assume is a trivial question. Appreciate your help, excited to use this library.

**Comment by donmstewart** [comment] 2019-04-27 15:06
I had the same problem. I used the following **(very unsafe)** fix to at least to get to code compilation stage: -

```
[[types]]
  # The match is a drivers.Column struct, and matches on almost all fields.
  # Notable exception for the unique bool. Matches are done
  # with "logical and" meaning it must match all specified matchers. Boolean values
  # are only checked if all the string specifiers match first, and they
  # must always match.
  # Not shown here: db_type is the database type and a very useful matcher
  [types.match]
    type = "int64"

  # The replace is what we replace the strings with. You cannot modify any
  # boolean values in here. But we could change the Go type (the most useful thing)
  # or the DBType or FullDBType etc. if for some reason we needed to.
  [types.replace]
    type = "int"
```

**Comment by aarondl** [comment] 2019-05-07 16:37
@subvertallchris This looks like a generation bug/problem in general that we should fix without needing to resort to type replacements. I think (but am unsure) it has to do with your primary key/foreign key types. Can you let me know what the actual id type you're using in postgres is so I can try this out?

That issue you linked is unlike yours, it is not a bug but just people's preference that it be one way or another (hence the suggestion of flags).

@donmstewart Was it the case that your models were not compiling as well? If so can you describe the problem a bit more? Just want to know types involved and whether or not they're primary/foreign keys.

**Comment by subvertallchris** [comment] 2019-05-10 14:17
Looking at my schema in the database and comparing it against my Rails migrations, I see I've got a mix of `integer` and `bigint` types floating around. I unfortunately no longer have the code that generated these errors and the piece of the error I posted was only a snippet, but I can see that it matches up.

Part of the issue appears to be an actual mismatch of types in Postgres. I can look at two tables, `locations` and `norms`. 

```
# \d locations;
                                      Table "public.locations"
    Column    |            Type             |                       Modifiers                        
--------------+-----------------------------+--------------------------------------------------------
 id           | integer                     | not null default nextval('locations_id_seq'::regclass)
```

```
# \d norms;
                                   Table "public.norms"
        Column        |            Type             |              Modifiers              
----------------------+-----------------------------+-------------------------------------
 id                   | uuid                        | not null default uuid_generate_v4()
 location_id          | bigint                      | not null
```

The `locations` table's ID is `int` but the foreign key is `bigint`. I'm quite certain that this is due to Rails 5.1's change to use bigint for all ids. The `locations` table was created using a Rails 5.0 migration and `norms` was 5.1. I bet that if I poked around a bit more, I'd find a couple other instances of this.

It appears that where Postgres and Ruby are concerned, this isn't a problem and they'll just convert types implicitly; Go doesn't seem as helpful. If that's the case, I'm not sure it's SQLBoiler's problem. I might need to fix this by finding a way to convert my int columns to bigint.

**Comment by aarondl** [comment] 2019-05-20 19:22
That makes sense. Thanks for the insights @subvertallchris. Going to close this as there doesn't appear to be much we can do here.

**Closed by aarondl** 2019-05-20 19:22 UTC

**Comment by donmstewart** [comment] 2019-05-21 08:29
Apologies for the delay in responding.

My issue was the same as @subvertallchris in that it was a number of FK to link tables where it was an `bigint` in the FK and an `int` in the link table.
