### ISSUE TITLE
types.NullDecimal with nil causes panic

### ISSUE THREAD

**Issue by andradei** [volatiletech/sqlboiler#404] opened 2018-10-23 18:35 UTC
Not a generation problem.

### What version of SQLBoiler are you using (`sqlboiler --version`)?

v3.0.1

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)

No

### If this happened at runtime what code produced the issue? (if not applicable leave blank)

```go
type MyStruct {
    Price types.NullDecimal
}

ms := &MyStruct{
    Price: types.NewNullDecimal(nil)
}

// This prints
// &MyStruct{
//     Price: Price:%!v(PANIC=runtime error: invalid memory address or nil pointer dereference)
// }
fmt.Printf("%#v\n", ms)

b, _ := json.Marshal(&ms) // panics here
```

### What is the output

runtime error: invalid memory address or nil pointer dereference

### Further information. What did you do, what did you expect?

It is expected that `d := types.NewNullDecimal(nil)` or `d := NullDecimal{}` or `var d NullDecimal` follow what its documentation states:

```go
// NullDecimal is the same as Decimal, but allows the Big pointer to be nil.
// See docmentation for Decimal for more details.
//
// When going into a database, if Big is nil it's value will be "null".
type NullDecimal struct {
	*decimal.Big
}
```

**Comment by aarondl** [comment] 2018-10-30 04:53
Hey there. This is a problem in the decimal library that we use. I've created an issue over there (you can see it referenced above) to see if we can't get a fix.

**Comment by andradei** [comment] 2018-11-14 22:52
Since the [author said we shouldn't be using his `decimal.Big` for JSON formatting](https://github.com/ericlagergren/decimal/issues/110#issuecomment-434811862), could the support for `nil` be coded in this package instead?

**Comment by aarondl** [comment] 2018-11-15 02:44
Yeah. It seems like maybe what we should do is add MarshalJSON/UnmarshalJSON to NullDecimal directly. Since it's a value type it will always be able to do the correct thing.

**Comment by andradei** [comment] 2018-12-11 19:23
The linked issue was closed, so one less panic to worry about.

**Comment by aarondl** [comment] 2019-03-18 18:00
cc @AlexDunmow

This is obviously still an issue. I'm actually wondering if we could go against the grain and use decimal.Big as a value type instead. It makes working with it more annoying since you'd have `&` wherever you use it as an input, but if you use it to start a calculation there should be no change thanks to go's automatic address of when using `.`

The pointer was a primary concern when I was choosing a decimal type to use for sqlboiler, I'm sad to see that the choice indeed is coming back to bite me.

For people who don't care and just want to work around the problem, you could probably type replace with https://github.com/shopspring/decimal which doesn't use a pointer and be okay.

**Comment by andradei** [comment] 2019-03-21 04:26
Usually, marshalling/unmarshalling already follows an API where you use references (`&Type`). So this should be a familiar API usage. I like that idea.

Sorry I haven't got around to look at it as I said. Life got super busy when I was supposed to be on vacation.

**Comment by AlexDunmow** [comment] 2019-03-21 04:54
In my opinion, https://github.com/shopspring/decimal  is the superior library, especially when having to do calculations.

**Comment by andradei** [comment] 2019-03-23 23:17
Interesting. It implements JSON marshalling/unmarshalling too. Maybe that isn't a concern, but the last commit was one year ago. Solid libraries usually get at those stages.

**Comment by aarondl** [comment] 2019-10-09 17:04
This should actually be fixed on dev as soon as I push today's changes.

**Closed** 2019-10-09 17:32 UTC
Labels: bug

**Comment by uded** [comment] 2021-03-13 15:16
Interestingly, I am running v4 and still have this issue.

I would support @AlexDunmow with the idea to migrate to a better library.

**Comment by aarondl** [comment] 2021-03-14 21:29
I think the issue is I never did push the bump to the version on the dev branch. My apologies. It should be there now.
