### ISSUE TITLE
Unable to scan null string array fields in postgres

### ISSUE THREAD

**Issue by ssherriff** [volatiletech/sqlboiler#200] opened 2017-08-31 02:29 UTC
I have a nullable field on Postgres defined as a text array field.

When I have a row where that text array field is set to null, and I try to query, I get the following error:

`models: failed to assign all query results to Platform slice: failed to bind pointers to obj: sql: Scan error on column index 9: boil: cannot convert <nil> to StringArray`

My model is being generated with the field as a `type.StringArray`, it looks as though that stops the field from being nullable.

If I then fill the field with values, so it is no longer NULL, the query works fine.

Thanks ahead of time for your help.

**Comment by aarondl** [comment] 2017-09-04 16:58
It looks to me like none of the implementations of arrays that we borrowed from allow for handling of nulls:
https://github.com/volatiletech/sqlboiler/blob/master/types/array.go#L459

This is troublesome. We already have a similar problem where arrays are decoding poorly in issue #178. We'll have to get around to this sooner rather than later. Thanks for the report.

**Comment by aarondl** [comment] 2017-09-13 13:56
Please test the branch `fix-arrays` to see if this issue is resolved for you.

**Comment by ssherriff** [comment] 2017-09-17 10:12
Hi Aaron, I've only briefly tested it, but it seems to fix it. There are a few cases I put in work arounds, so I'll find those and revert them, and see if it works okay for all of those cases as well. Initial testing is good though!
Thanks

**Comment by ssherriff** [comment] 2017-09-21 03:21
Reading of arrays seems to work, but while I have `fix arrays` checked out, I'm unable to regenerate my sqlboiler files as I receive the following error:

`
Error: template: 00_struct.tpl:12:15: executing "00_struct.tpl" at <$dot.StructTagCasing>: can't evaluate field StructTagCasing in type *boilingcore.templateData
failed to execute template: 00_struct.tpl
github.com/volatiletech/sqlboiler/boilingcore.executeTemplate
        /Users/StephMacbook/Workarea/Go/src/github.com/volatiletech/sqlboiler/boilingcore/output.go:231
github.com/volatiletech/sqlboiler/boilingcore.executeTemplates
        /Users/StephMacbook/Workarea/Go/src/github.com/volatiletech/sqlboiler/boilingcore/output.go:117
github.com/volatiletech/sqlboiler/boilingcore.generateOutput
        /Users/StephMacbook/Workarea/Go/src/github.com/volatiletech/sqlboiler/boilingcore/output.go:44
github.com/volatiletech/sqlboiler/boilingcore.(*State).Run
        /Users/StephMacbook/Workarea/Go/src/github.com/volatiletech/sqlboiler/boilingcore/boilingcore.go:154
main.run
        /Users/StephMacbook/Workarea/Go/src/github.com/volatiletech/sqlboiler/main.go:309
github.com/spf13/cobra.(*Command).execute
        /Users/StephMacbook/Workarea/Go/src/github.com/spf13/cobra/command.go:650
github.com/spf13/cobra.(*Command).ExecuteC
        /Users/StephMacbook/Workarea/Go/src/github.com/spf13/cobra/command.go:729
github.com/spf13/cobra.(*Command).Execute
        /Users/StephMacbook/Workarea/Go/src/github.com/spf13/cobra/command.go:688
main.main
        /Users/StephMacbook/Workarea/Go/src/github.com/volatiletech/sqlboiler/main.go:104
runtime.main
        /usr/local/Cellar/go/1.8.3/libexec/src/runtime/proc.go:185
runtime.goexit
        /usr/local/Cellar/go/1.8.3/libexec/src/runtime/asm_amd64.s:2197
unable to generate output
github.com/volatiletech/sqlboiler/boilingcore.(*State).Run
        /Users/StephMacbook/Workarea/Go/src/github.com/volatiletech/sqlboiler/boilingcore/boilingcore.go:155
main.run
        /Users/StephMacbook/Workarea/Go/src/github.com/volatiletech/sqlboiler/main.go:309
github.com/spf13/cobra.(*Command).execute
        /Users/StephMacbook/Workarea/Go/src/github.com/spf13/cobra/command.go:650
github.com/spf13/cobra.(*Command).ExecuteC
        /Users/StephMacbook/Workarea/Go/src/github.com/spf13/cobra/command.go:729
github.com/spf13/cobra.(*Command).Execute
        /Users/StephMacbook/Workarea/Go/src/github.com/spf13/cobra/command.go:688
main.main
        /Users/StephMacbook/Workarea/Go/src/github.com/volatiletech/sqlboiler/main.go:104
runtime.main
        /usr/local/Cellar/go/1.8.3/libexec/src/runtime/proc.go:185
runtime.goexit
        /usr/local/Cellar/go/1.8.3/libexec/src/runtime/asm_amd64.s:2197
`

**Comment by aarondl** [comment] 2017-10-01 11:38
@ssherriff It seems like you have a bad version of the templates. This is usually caused by multiple checkouts. Remember that `sqlboiler` will always look inside `$GOPATH/src/github.com/volatiletech/sqlboiler/templates` to find it's templates, even if it's compiled as a binary.

**Comment by aarondl** [comment] 2017-11-11 23:46
Resolved in latest release 6b95e5d. Open new issue for other problems :)

**Closed by aarondl** 2017-11-11 23:46 UTC
