### ISSUE TITLE
use wrong index when generate code

### ISSUE THREAD

**Issue by aaabbbccc-123** [volatiletech/sqlboiler#408] opened 2018-10-29 07:16 UTC
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?

SQLBoiler v3.0.1

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
sqlboiler mysql

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
boiler database:
CREATE TABLE `envs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL DEFAULT '' unique,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4

test database:
CREATE TABLE `envs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4

### Further information. What did you do, what did you expect?
generate code against test database. u can notice that envs.name is marked as unique when it is not.

**Comment by aarondl** [comment] 2018-10-30 06:10
I'm trying to figure out what the issue is here I don't fully understand.

When you say `boiler` database what is that? And `test` database, is that the one created by `sqlboiler` when you do `go test ./models` or..?

I do see envs.name marked as unique in the example you've given above... so wouldn't it be correct that it's unique?

**Comment by aaabbbccc-123** [comment] 2018-10-31 01:50
there are two database in the mysql server. and i try to generate code from the second one `test`. in test.envs , the name column does not have unique.

**Comment by aarondl** [comment] 2018-11-08 06:00
I think I got this now. It's on the dev branch, feel free to test it :)

**Closed** 2018-12-26 10:41 UTC
