### ISSUE TITLE
cannot take address of one.Group

### ISSUE THREAD

**Issue by louis77** [volatiletech/sqlboiler#411] opened 2018-11-02 11:00 UTC
sqlboiler generates relations to tables which have a column named "group" (I know I know, legacy and unchangeable). However, I've aliased all these columns to GroupID which works fine for the models themself. However, in the LoadXYZ function (eager loading of related rows) the code generated doesn't use the alias. The result is:

```go
	var localJoinCols []string
	for results.Next() {
		one := new(Feature)
		var localJoinCol string
                // Problem starts here:
                // &one.Group is a function not the column aliased to GroupID
                // is should be results.Scan(&one.GroupID, ...)
		err = results.Scan(&one.Group, &one.Name, &one.Translations, &one.IconURL, &one.ID, &one.CreatedAt, &one.UpdatedAt, &localJoinCol)
		if err != nil {
			return errors.Wrap(err, "failed to scan eager loaded results for features")
		}
		if err = results.Err(); err != nil {
			return errors.Wrap(err, "failed to plebian-bind eager loaded slice features")
		}
```

This results in compilation errors:
```
models/accommodationmasters.go:711:22: cannot take the address of one.Group
models/features.go:509:22: cannot take the address of one.Group
```

### What version of SQLBoiler are you using (`sqlboiler --version`)?
Tried with 3.0.0 and 3.0.1

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
`sqlboiler psql --no-tests --wipe -o models -p models`

**Comment by aarondl** [comment] 2018-11-08 05:31
Looks like a duplicate of #415

**Closed by aarondl** 2018-11-08 05:31 UTC
