### ISSUE TITLE
"sqlboiler psql" fails with "runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by bbruun** [volatiletech/sqlboiler#1146] opened 2022-06-07 09:11 UTC
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?

```bash
$ sqlboiler --version
SQLBoiler v4.11.0
```

Installed today, June 7th 2022.

### What is your database and version (eg. Postgresql 10)

```bash
$ dpkg -l | grep "postgresql-[0-9]"
ii  postgresql-12                         12.11-0ubuntu0.20.04.1                amd64        object-relational SQL database, version 12 server
```

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)

```bash
$ sqlboiler psql     
runtime error: invalid memory address or nil pointer dereference
Error: unable to initialize tables: unable to fetch table data: driver (/home/myuser/go/bin/sqlboiler-psql) exited non-zero: exit status 1
```

```bash
$ ls -l ~/go/bin/sqlboiler*    
-rwxrwxr-x 1 myuser myuser 11542972 Jun  7 10:43 /home/myuser/go/bin/sqlboiler
-rwxrwxr-x 1 myuser myuser  6901514 Jun  7 10:43 /home/myuser/go/bin/sqlboiler-psql
```

### What is the output of the command above with the `-d` flag added to it? (Provided you are comfortable sharing this, it contains a blueprint of your schema)

```bash
$ sqlboiler psql -d                                         
using driver: /home/myuser/go/bin/sqlboiler-psql
runtime error: invalid memory address or nil pointer dereference
{"config":{"driver_name":"psql","driver_config":{"add-enum-types":false,"blacklist":null,"dbname":"restore-test","enum-null-prefix":"Null","host":"diana","pass":"buller45","port":5432,"sslmode":"disable","user":"properson","whitelist":null},"pkg_name":"models","out_folder":"models","debug":true,"enum_null_prefix":"Null","no_tests":true,"wipe":true,"struct_tag_casing":"snake","relation_tag":"-","imports":{"all":{"Standard":["\"database/sql\"","\"fmt\"","\"reflect\"","\"strings\"","\"sync\"","\"time\""],"ThirdParty":["\"github.com/friendsofgo/errors\"","\"github.com/volatiletech/sqlboiler/v4/boil\"","\"github.com/volatiletech/sqlboiler/v4/queries\"","\"github.com/volatiletech/sqlboiler/v4/queries/qm\"","\"github.com/volatiletech/sqlboiler/v4/queries/qmhelper\"","\"github.com/volatiletech/strmangle\""]},"test":{"Standard":["\"bytes\"","\"reflect\"","\"testing\""],"ThirdParty":["\"github.com/volatiletech/sqlboiler/v4/boil\"","\"github.com/volatiletech/sqlboiler/v4/queries\"","\"github.com/volatiletech/randomize\"","\"github.com/volatiletech/strmangle\""]},"singleton":{"boil_queries":{"Standard":null,"ThirdParty":["\"github.com/volatiletech/sqlboiler/v4/drivers\"","\"github.com/volatiletech/sqlboiler/v4/queries\"","\"github.com/volatiletech/sqlboiler/v4/queries/qm\""]},"boil_types":{"Standard":["\"strconv\""],"ThirdParty":["\"github.com/friendsofgo/errors\"","\"github.com/volatiletech/sqlboiler/v4/boil\"","\"github.com/volatiletech/strmangle\""]}},"test_singleton":{"boil_main_test":{"Standard":["\"database/sql\"","\"flag\"","\"fmt\"","\"math/rand\"","\"os\"","\"path/filepath\"","\"strings\"","\"testing\"","\"time\""],"ThirdParty":["\"github.com/spf13/viper\"","\"github.com/volatiletech/sqlboiler/v4/boil\""]},"boil_queries_test":{"Standard":["\"bytes\"","\"fmt\"","\"io\"","\"io/ioutil\"","\"math/rand\"","\"regexp\""],"ThirdParty":["\"github.com/volatiletech/sqlboiler/v4/boil\""]},"boil_suites_test":{"Standard":["\"testing\""],"ThirdParty":null}}},"aliases":{},"auto_columns":{},"inflections":{"Plural":{},"PluralExact":{},"Singular":{},"SingularExact":{},"Irregular":{}},"version":"4.11.0"},"driver_config":{"add-enum-types":false,"blacklist":null,"dbname":"restore-test","enum-null-prefix":"Null","host":"diana","pass":"buller45","port":5432,"sslmode":"disable","user":"properson","whitelist":null},"schema":"","dialect":{"lq":0,"rq":0,"use_index_placeholders":false,"use_last_insert_id":false,"use_schema":false,"use_default_keyword":false,"use_top_clause":false,"use_output_clause":false,"use_case_when_exists_clause":false,"use_auto_columns":false},"tables":null,"templates":null}
Error: exit status 1
driver (/home/myuser/go/bin/sqlboiler-psql) exited non-zero
github.com/volatiletech/sqlboiler/v4/drivers.execute
        /home/myuser/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.11.0/drivers/binary_driver.go:73
github.com/volatiletech/sqlboiler/v4/drivers.binaryDriver.Assemble
        /home/myuser/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.11.0/drivers/binary_driver.go:21
github.com/volatiletech/sqlboiler/v4/boilingcore.(*State).initDBInfo
        /home/myuser/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.11.0/boilingcore/boilingcore.go:408
github.com/volatiletech/sqlboiler/v4/boilingcore.New
        /home/myuser/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.11.0/boilingcore/boilingcore.go:86
main.preRun
        /home/myuser/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.11.0/main.go:219
github.com/spf13/cobra.(*Command).execute
        /home/myuser/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:845
github.com/spf13/cobra.(*Command).ExecuteC
        /home/myuser/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974
github.com/spf13/cobra.(*Command).Execute
        /home/myuser/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
main.main
        /home/myuser/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.11.0/main.go:122
runtime.main
        /usr/lib/go-1.18/src/runtime/proc.go:250
runtime.goexit
        /usr/lib/go-1.18/src/runtime/asm_amd64.s:1571
unable to fetch table data
github.com/volatiletech/sqlboiler/v4/boilingcore.(*State).initDBInfo
        /home/myuser/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.11.0/boilingcore/boilingcore.go:410
github.com/volatiletech/sqlboiler/v4/boilingcore.New
        /home/myuser/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.11.0/boilingcore/boilingcore.go:86
main.preRun
        /home/myuser/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.11.0/main.go:219
github.com/spf13/cobra.(*Command).execute
        /home/myuser/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:845
github.com/spf13/cobra.(*Command).ExecuteC
        /home/myuser/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974
github.com/spf13/cobra.(*Command).Execute
        /home/myuser/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
main.main
        /home/myuser/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.11.0/main.go:122
runtime.main
        /usr/lib/go-1.18/src/runtime/proc.go:250
runtime.goexit
        /usr/lib/go-1.18/src/runtime/asm_amd64.s:1571
unable to initialize tables
github.com/volatiletech/sqlboiler/v4/boilingcore.New
        /home/myuser/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.11.0/boilingcore/boilingcore.go:88
main.preRun
        /home/myuser/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.11.0/main.go:219
github.com/spf13/cobra.(*Command).execute
        /home/myuser/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:845
github.com/spf13/cobra.(*Command).ExecuteC
        /home/myuser/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974
github.com/spf13/cobra.(*Command).Execute
        /home/myuser/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
main.main
        /home/myuser/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.11.0/main.go:122
runtime.main
        /usr/lib/go-1.18/src/runtime/proc.go:250
runtime.goexit
        /usr/lib/go-1.18/src/runtime/asm_amd64.s:1571

```

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)

It does not even load the sqlboiler.toml file which has been unchanged since sqlboiler version v3.7.1 and v4.2 where it worked. 
This is something that stopped working with sqlboiler v4.11.0 after update.

### Further information. What did you do, what did you expect?

I updated SQL Boiler as per the documentation  aka ran
* `go install github.com/volatiletech/sqlboiler/v4@latest`
* `go install github.com/volatiletech/sqlboiler/v4/drivers/sqlboiler-psql@latest`

I don't know how to downgrade again as the go install version parameter just complains if I try to add a specific version eg @v4.10.2.

Any help would be appreciated.

**Comment by bbruun** [comment] 2022-06-07 11:51
Found out how to install v4.10.2 and it does not crash with the above runtime error
```
go install github.com/volatiletech/sqlboiler/v4@v4.10.2
go install github.com/volatiletech/sqlboiler/v4/drivers/sqlboiler-psql@v4.10.2
```

**Comment by wk8** [comment] 2022-06-09 16:37
Encountered the same; and while @bbruun's suggestion of downgrading works, would be nice if we could get to the root cause of this so that we don't have to stick with the same version going forward :)

So maybe reopen this?

**Comment by stephenafamo** [comment] 2022-06-09 19:06
I'll reopen this, sadly I don't have the time to debug this right now. I'll add a `help wanted` so any volunteer can pick it up.

**Comment by zapo** [comment] 2022-06-16 19:56
@wk8 Do you happen to miss a pkey in one of your tables ? If that's the case, and adding the missing pkey fixes the panic it should be fixed by https://github.com/volatiletech/sqlboiler/pull/1140 and in the next release.

**Comment by stephenafamo** [comment] 2022-07-26 03:52
I believe this was caused by a missing primary key and has been fixed in the most recent release. I'll close this now. Let me know if the problem persists

**Closed by stephenafamo** 2022-07-26 03:52 UTC
Labels: bug, help wanted
