### ISSUE TITLE
Question passing an Int slice into WhereIn

### ISSUE THREAD

**Issue by fi0** [volatiletech/sqlboiler#227] opened 2017-11-25 02:41 UTC
how do I pass a slice into whereIn? 

example
`qm.WhereIn("id in ?", 1, 2, 3)`

these won't work
```
ids := []int{1, 2, 3}
qm.WhereIn("id in ?", ids)
```
```
ids := []int{1, 2, 3}
qm.WhereIn("id in ?", ids...)
```

**Comment by aarondl** [comment] 2017-11-25 03:42
The bottom one should be working, can you turn on debug mode and show what kind of query or error you're getting? Need more information to determine what the problem is :)

**Comment by payaaam** [comment] 2017-11-30 01:28
I have had problems with this too. The solution is to convert your slice to `[]interface{}`.

*Example*
```go
ids := []int{1, 2, 3}
convertedIDs := make([]interface{}, len(ids))
for index, num := range ids {
	convertedIDs[index] =  num
}

qm.WhereIn("id IN ?", convertedIDs...)
```

**Comment by fi0** [comment] 2017-12-02 14:40
thank you it works

**Comment by aarondl** [comment] 2017-12-08 04:21
I actually think we should try to fix this. It shouldn't really behave like this and we may be able to do something about it.

**Comment by ceshihao** [comment] 2017-12-20 14:09
This problem is from golang/go#16235
It seems to be fixed in go1.9 by supporting custom import types.

**Closed** 2018-06-04 15:59 UTC
Labels: planned

**Comment by tonyhb** [comment] 2020-02-21 18:49
@aarondl I'm pretty sure we can fix this with a quick bit of reflection.

Right now we always expect that a user splats their variadic arg.  That's the root cause of the issue. 

For argument's sake, lets allow people to call WhereIn with a slice (`qm.WhereIn("id IN ?", ids)` where ids is a slice).

Then, we inspect our variadic argument to see if `len` is 1.  If so, we _may_ have a slice passed.  We can then fix WhereIn as follows:

```
func WhereIn(clause string, args ...interface{}) QueryMod {
	if len(args) == 1 && reflect.TypeOf(args[0]).Kind() == reflect.Slice {
		val := reflect.ValueOf(args[0])
		slice := make([]interface{}, val.Len())
		for i := 0; i < val.Len(); i++ {
			slice[i] = val.Index(i)
		}
		return WhereIn(clause, slice...)
	}

	fmt.Printf("continue: %vv", args)
}
```

We use reflect to see if the only item in `arg` is a slice, and if so we handle the conversion of slice to interfaces for people automatically.  Type safe, no impact, better UX.

I'll make a PR now

**Comment by tonyhb** [comment] 2020-02-21 18:49
Here's a quick demo: https://play.golang.org/p/0rrgz5cwFtj

**Comment by JC1738** [comment] 2023-03-13 04:07
Still doesn't work unless you use something like this

`func ToSliceOfAny[T any](s []T) []any {
    result := make([]any, len(s))
    for i, v := range s {
        result[i] = v
    }
    return result
}`
