### ISSUE TITLE
[Feature Request] OneOrNone

### ISSUE THREAD

**Issue by tzachshabtay** [volatiletech/sqlboiler#452] opened 2018-12-31 20:44 UTC
A `OneOrNone` API to complement the already existing `One` function would be really useful.

The idea is that `OneOrNone` expects either 0 or 1 rows to be returned, so the signature is identical to `One` only you should check for `nil` in your returning object (and you shouldn't get an error if the object was not found).

`pg-promise`, for example, have this API, [see here](https://vitaly-t.github.io/pg-promise/Database.html#oneOrNone).

**Comment by aarondl** [comment] 2019-01-02 17:57
Duplicate of #450 discussion.

**Closed by aarondl** 2019-01-02 17:57 UTC
