### ISSUE TITLE
Enum Type is not generated when referenced to a Table as a StringArray

### ISSUE THREAD

**Issue by bryanmcgrane** [volatiletech/sqlboiler#1090] opened 2022-02-16 20:57 UTC
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
`SQLBoiler v4.8.6`

### What is your database and version (eg. Postgresql 10)
`Postgres 12`

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
`sqlboiler psql`

### What is the output of the command above with the `-d` flag added to it? (Provided you are comfortable sharing this, it contains a blueprint of your schema)

            {
               "name":"compression",
               "type":"types.StringArray",
               "db_type":"ARRAYUSER-DEFINED",
               "default":"NULL",
               "comment":"",
               "nullable":true,
               "unique":false,
               "validated":false,
               "auto_generated":false,
               "arr_type":"USER-DEFINED",
               "udt_name":"_CompressionType",
               "domain_name":null,
               "full_db_type":"_CompressionType"
            },

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
```
-- CreateEnum
CREATE TYPE "CompressionType" AS ENUM ('IMAGE_GRAYSCALE');

-- CreateTable
CREATE TABLE "Enrollment" (
    "id" UUID NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "description" VARCHAR(1023) NOT NULL,
    "compression" "CompressionType"[],

    PRIMARY KEY ("id")
);
```

### Further information. What did you do, what did you expect?
I added the CompressionType on a temporary column for testing:
```
-- AlterTable
ALTER TABLE "Enrollment" ADD COLUMN     "compressionTest" "CompressionType" NOT NULL;

```

Then I reran `sqlboiler psql` and the type was generated for me.

**Comment by stephenafamo** [comment] 2022-02-17 10:39
I'll close this as a duplicate of #739. A PR would be appreciated.

**Closed by stephenafamo** 2022-02-17 10:39 UTC
